### ISSUE TITLE
VolumeControllが正しく動いていない

### ISSUE THREAD

**Issue by gmkou** [gmkou/MusicPi#3]
なんか動かすとエラーが出てる。

**Comment by sassy** [comment]
たぶん、クラス変数のアクセス方法が間違っている
`Player._volume` で参照しないと行けない。

**Comment by gmkou** [comment]
fix at 9d40a7d138f39e62813cf4edac506ccaea9c3858
fifoのファイルを用意し、そこをインプットにするようにした。
